question_data = [
    {
        "category": "General Knowledge",
        "type": "boolean", "difficulty": "easy",
        "question": "The Great Wall of China is visible from the moon.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    },
    {
        "category": "Animals", "type": "boolean", "difficulty": "easy",
        "question": "Kangaroos keep food in their pouches next to their children.",
        "correct_answer": "False", "incorrect_answers": ["True"]
    },
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "Tetris is the #1 best-selling video game of all-time.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
     "difficulty": "easy",
     "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "George Lucas directed the entire original Star Wars trilogy.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Slovakia is a member of European Union-", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "There are a total of 20 races in Formula One 2016 season.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
